name: Sabadwani App

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Web Assets
        run: |
          # GitHub Secret से .env बनाना (React के लिए)
          echo "${{ secrets.ENV_FILE }}" > .env
          npm run build

      - name: Sync Android (Using Local Config)
        run: |
          # सिर्फ JSON फाइल को इन्जेक्ट कर रहे हैं
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json
          
          # Capacitor को अपडेट करना
          npx cap sync android

       Pentesting / Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build Signed APK & AAB
        working-directory: ./android
        run: |
          chmod +x gradlew
          
          # Keystore को डिकोड करना
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > app/sabadwani.keystore
          
          ./gradlew clean assembleRelease bundleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/app/sabadwani.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Rename and Prepare Files
        run: |
          mkdir -p build-output
          find android/app/build/outputs/apk/release/ -name "*.apk" -exec cp {} build-output/Sabadwani.apk \;
          find android/app/build/outputs/bundle/release/ -name "*.aab" -exec cp {} build-output/Sabadwani.aab \;

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Sabadwani-APP
          path: build-output/